fix(cli): Install server package in the cli container to inlcude lerc. (#3353)
### Motivation

The [cli
container](https://github.com/linz/basemaps-config/actions/runs/11096451992/job/30827033370?pr=984)
requires lerc to be installed which come from server.

`
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'lerc'
Require stack:
- /app/index.cjs
at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/index.cjs:190419:27)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
at Function.executeUserEntryPoint [as runMain]
(node:internal/modules/run_main:[174](https://github.com/linz/basemaps-config/actions/runs/11096451992/job/30827033370?pr=984#step:6:175):12)
{
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/index.cjs' ]
}
`

### Modifications
Install serve package in the cli container.

### Verification
Container fixed after install server package, add smoke test in the
container ci/cd for validation