fix: correct cli-config 'import' parameters (#3445)
### Motivation

In an [earlier piece of work], we converted the `import` command from
[rushstack] to [cmd-ts]. In doing so, we mistakenly converted the
`output` parameter from an **optional** string, to a **non-optional**
string.

This causes the basemaps-config's [Deploy Nonprod] job to fail. The
[failing command] and error are as follows:

```yml
- name: Import config
  run: |
    ./scripts/bmc.sh ./index.cjs config import --config ${CONFIG_PATH} --commit
```

```
error: found 1 error

  1. No value provided for --output
```

### Modifications

1. Updated the `cli-config` package's `import`command's `output`
parameter to an **optional** string.
2. Added missing references to the `cli` package's `tsconfig.json` file
to resolve type declaration errors.
3. Re-ordered the root `tsconfig.json` file's references for easier
maintenance.

### Verification

I've captured a screenshot showing that the `import` command's `output`
parameter is now optional:

![][img-output-param]

I've also tested the `import` command locally with the `--commit` flag
omitted. The command does require a valid `config`, so I used a random
one from the S3 bucket:

```
node packages/cli/bin/bmc.js config import --config s3://linz-basemaps/config/config-28Fp43sn1XCmsh9QX6hwsyKESrm6e67PkG3agcVWmLEv.json.gz
```

We can see that the command executes successfully without requiring the
`output` parameter:

```
...
[2025-05-14T02:08:06.137Z] INFO Change:Update type=ts record=ts_all description=all commit=false
[2025-05-14T02:08:06.137Z] INFO Import:Compare:Done objects=820 types={ ts=492 st=5 pv=1 im=322 }
[2025-05-14T02:08:06.138Z] INFO DryRun:Done
```
<!-- external links -->

[earlier piece of work]:
https://github.com/linz/basemaps/pull/3427/commits/01a90a2b98bab02632a9637bfed2067c9c047c61#diff-48a5e932b724482f9a280931b7bb1188d26ef004b87c331aadfc7a7948ec7f70

[rushstack]: https://github.com/microsoft/rushstack
[cmd-ts]: https://github.com/Schniz/cmd-ts

[Deploy Nonprod]:
https://github.com/linz/basemaps-config/actions/runs/15007294128/job/42168979816

[failing command]:
https://github.com/linz/basemaps-config/blob/a5b8b9baaa9941314a13058e53945bc5db5f5357/.github/workflows/build.yml#L131

[img-output-param]:
https://github.com/user-attachments/assets/ddffcbbc-950d-44d8-af67-1b2d0149289d